### ISSUE TITLE
Payload problem

### ISSUE THREAD

**Issue by sahbbin** [SensorsIot/MQTT-meets-Sonoff#1]

**Comment by sahbbin** [comment]
I am using the sketch from your MQTT video bu I keep getting different payloads each time I test the mqtt. Instead of getting the ON payload, the message is followed by characters and so the esp32 does not recognise the payload. How can I fix thsi issue? 

> **

 Message received **
  topic: cmnd/home/power  feedbackTopic: cmnd/home/power  qos: 1  dup: 0  retain: 0  len: 2  index: 0  payload: ON⸮⸮? ⸮⸮?⸮⸮!ﾭ⸮xV⸮⸮
Publishing Feedback
** Published  packetId: 51

** Message received **
  topic: cmnd/home/power  feedbackTopic: cmnd/home/power  qos: 1  dup: 0  retain: 0  len: 2  index: 0  payload: ON⸮⸮? ⸮⸮?
Publishing Feedback
** Published  packetId: 52

** Message received **
  topic: cmnd/home/power  feedbackTopic: cmnd/home/power  qos: 1  dup: 0  retain: 0  len: 2  index: 0  payload: ON⸮$
⸮⸮ظ'⸮⸮ﾭ⸮xV⸮⸮ 
Publishing Feedback
** Published  packetId: 53

> @SensorsIot

**Comment by SensorsIot** [comment]
Unfortunately, I cannot provide application support. But you can print the message you send in the ESP32 and check what arrives. Maybe then you will find where the problem happens.
